services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: webapp_docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  postgres:
    restart: always
    image: postgres
    container_name: postgres_docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    volumes:
      - ./data:/var/lib/postgresql/postgresql_data
  redis:
    restart: always
    image: redis
    container_name: redis_docker
    ports:
      - "6379:6379"
    volumes:
      - ./data:/redis_data/redis_data
